# Generated by Django 5.0.6 on 2024-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdiscussion",
            name="support_file",
            field=models.FileField(null=True, upload_to="comments_files/"),
        ),
    ]
