# Generated by Django 5.0.6 on 2024-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectdiscussion_support_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdiscussion",
            name="commentor",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
