# Generated by Django 5.0.6 on 2024-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Admin", "ADMIN_USER"), ("User", "USER")], max_length=255
            ),
        ),
    ]
