# Generated by Django 5.0.6 on 2024-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_remove_postcomment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
