# Generated by Django 5.0.6 on 2024-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_question_response_survey_post_meeting_link_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="required_votes",
            field=models.IntegerField(default=200),
        ),
    ]
